export const CHANGE_CATEGORY = "CHANGE_CATEGORY";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";

export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_SORTING_SUCCESS = "GET_SORTING_SUCCESS";
export const CHANGE_SORTING_SUCCESS = "CHANGE_SORTING_SUCCESS";

export const ADD_TO_CART = "ADD_TO_CART";
export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export const GET_COMPANY_SUCCESS = "GET_COMPANY_SUCCESS";
export const CHANGE_COMPANY_SUCCESS = "CHANGE_COMPANY_SUCCESS";
